// This file is @generated by prost-build.
/// 公共事件
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventCommon {
    /// 事件类型：1 删除系统公告 2语音播报 3ding已读
    #[prost(int32, tag = "1")]
    pub r#type: i32,
    /// 事件内容，json结构，示例：{"notice_id": 100}
    #[prost(string, tag = "2")]
    pub data: ::prost::alloc::string::String,
}
/// 消息发送
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSend {
    /// 消息类型，1：文字
    #[prost(int32, tag = "1")]
    pub r#type: i32,
    /// 消息内容
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
    /// 用户id或者群组id
    #[prost(uint64, tag = "3")]
    pub to_id: u64,
    /// 接收者类型
    #[prost(bool, tag = "4")]
    pub is_room: bool,
    /// 额外信息map 可解析的json字符串
    #[prost(string, tag = "5")]
    pub meta: ::prost::alloc::string::String,
}
/// 消息发送回执
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSendAck {
    /// 服务器消息id
    #[prost(uint64, tag = "1")]
    pub msg_id: u64,
    /// 错误原因
    #[prost(string, tag = "2")]
    pub err_msg: ::prost::alloc::string::String,
}
/// 设备退出登录
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Logout {
    /// 退出登录原因
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
/// 设备登录
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignIn {
    /// 设备token
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    /// 设备token
    #[prost(string, tag = "2")]
    pub sign: ::prost::alloc::string::String,
    /// 不推送离线
    #[prost(bool, tag = "3")]
    pub not_push: bool,
    /// app version
    #[prost(string, tag = "4")]
    pub app_version: ::prost::alloc::string::String,
}
/// 设备登录回执
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignInAck {
    #[prost(uint64, tag = "1")]
    pub device_id: u64,
    #[prost(uint64, tag = "2")]
    pub user_id: u64,
    /// 描述
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    /// 连接时间
    #[prost(int64, tag = "4")]
    pub connect_time: i64,
}
